function NARR_SEUS_SWRadiation_1hr1km_CloudCorr(iyear,startday,endday)
% Cloudiness correction to NARR solar radiation via reproducing the large-scale 
% spatial pattern observed by GSRB through PDF matching.
%--------------------------------------------------------------------------
% By Jing Tao, Duke University
% Last updated: 10/10/2013
%--------------------------------------------------------------------------

data24hr=rand(610,716,24);srb24hr=rand(610,716,24);
%--------------------------------------------------------------------------
narr_dir='/home/jt85/HMT-SEUS/Mat/SEUS_NARR_1hr1km_UTM_SW_Anci/';
szn_dir='/home/jt85/HMT-SEUS/Program/Albedo_Ancillary/SZN_1km1hr/';
topszn_dir='/home/jt85/HMT-SEUS/Program/Albedo_Ancillary/SZN_1km1hr_TopHourTemp/';
botszn_dir='/home/jt85/HMT-SEUS/Program/Albedo_Ancillary/SZN_1km1hr_BotHourTemp/';
srb_dir='/home/jt85/HMT-SEUS/Mat/SEUS_SRB_1hr1km_UTM_EST/';    
geo_dir='/home/jt85/HMT-SEUS/Program/Geo/';
load([geo_dir,'DEM_SE_US_1000m_UTM.mat']);%cdem
home_dir='/home/jt85/HMT-SEUS/Program/';addpath(home_dir);
outnm='shortwave_Final_from1hrSpatialPdfCorr';

% for iyear=2007:2011
%-----------------------------------------------
dirtmp=dir(srb_dir);fnmls=[];
for i=3:length(dirtmp);fnmls(i-2,:)=dirtmp(i).name;end 
startstep=(sum(yeardays(2007:iyear-1))+startday-1)*24+1;
endstep=startstep+(endday-startday+1)*24-1;
for ii=startstep:24:endstep
    data24hr(:,:,:)=NaN;srb24hr(:,:,:)=NaN;datahr=zeros(1,24);
    for j=1:24 %local time,EST
        fstr=fnmls(ii+j-1+5,:);%UTC+5
        load([szn_dir,fstr(1:4),'/',fstr]);cszn=cos(szn*pi/180);
        load([topszn_dir,fstr(1:4),'/',fstr]);topcszn=cos(szn*pi/180);
        load([botszn_dir,fstr(1:4),'/',fstr]);botcszn=cos(szn*pi/180);
        %Night time as 0
        if j<12; cszn(botcszn<0)=0;%morning
        cszn(cszn<0&botcszn>=0)=botcszn(cszn<0&botcszn>=0)/2.0;    
        else cszn(topcszn<0)=0; %afternoon
        cszn(cszn<0&topcszn>=0)=topcszn(cszn<0&topcszn>=0)/2.0;     
        end
        if (numel(cszn(cszn>0&isnan(cdem)==0))==numel(cszn(isnan(cdem)==0)));datahr(j)=1;end %day time =1, night time =0
            
        %Generated byNARR_SEUS_SWRadiation_1hr1km_SZN.m
        load([narr_dir,fstr(1:4),'/',fstr(1:10),'/shortwave_SZNInt_SQSW_NoSun_Final.mat']);%'data','cszn'
        %GSRB data:
        fnameii = [srb_dir,fnmls(ii+j-1,:)]; %EST
        load(fnameii);%prearea
        %----------------
        if numel(prearea(isnan(prearea)))>numel(prearea)/10%missing area is larger than 1/10 of the region
            prearea(:,:)=NaN; %No matter night or day time
        elseif numel(prearea(isnan(prearea)))>0&&numel(prearea(isnan(prearea)==1))<=numel(prearea)/10; %missing area is less than 1/10 of the region
            prearea=fillmatrix_spatial(prearea,cszn);
        end 
        %NO Partially missing exist!!!Causing discontinuty
        %---------------
        if (numel(cszn(cszn>0&isnan(cdem)==0))==numel(cszn(isnan(cdem)==0)))&&(numel(prearea(isnan(prearea)==1))==numel(prearea))
            datahr(j)=NaN; %All missing during daytime
        elseif (numel(cszn(cszn>0&isnan(cdem)==0))==numel(cszn(isnan(cdem)==0)))&&(numel(prearea(isnan(prearea)==0))==numel(prearea))
            datahr(j)=2; %No missing during daytime
        end
        
        data24hr(:,:,j)=data;
        srb24hr(:,:,j)=prearea;
    end
    
    %===============================================    
    nomissidx=find(datahr==2);%day time, no missing at all
    if ~isempty(nomissidx)
        for j=1:24     
        srbdata(:,:)=srb24hr(:,:,j);
        shortwave(:,:)=data24hr(:,:,j);
        NARRcorrSW=shortwave;
        
        if datahr(j)~=0 %daytime
        shortwavetmp=shortwave;
        shortwavetmp(isnan(cdem)==1)=NaN;    
        %------------------------------   
        if numel(srbdata(isnan(srbdata)))>0 
            idnomiss = knnsearch(nomissidx',j,'k',1);ID=nomissidx(idnomiss);
            tmp=srb24hr(:,:,ID);
%             if datahr(j)==1 %Partially missing during daytime
%                 srbdata=matrixop(srbdata,tmp,'mean');
%             elseif isnan(datahr(j))==1 %Totally missing
%                 srbdata=tmp;
%             end
            srbdata=tmp;
        end
        
        RSmx=nanmax(srbdata(:));RSmin=nanmin(srbdata(:));
        Rindex=(RSmx-srbdata)/(RSmx-RSmin);
        Rmx=nanmax(shortwavetmp(:));Rmin=nanmin(shortwavetmp(:));
        NARRcorrSW=Rmx-Rindex*(Rmx-Rmin);
        %------------------------------   
        end
        
        fstr=fnmls(ii+j-1+5,:);%UTC+5
        save([narr_dir,fstr(1:4),'/',fstr(1:10),'/',outnm,'.mat'],'NARRcorrSW');
        end
    else %a whole day is missing
        for j=1:24    
        NARRcorrSW(:,:)=data24hr(:,:,j);
        fstr=fnmls(ii+j-1+5,:);%UTC+5  
        save([narr_dir,fstr(1:4),'/',fstr(1:10),'/',outnm,'.mat'],'NARRcorrSW');
        end
    end
end
% end
cd(home_dir);

end

%% ------------------------------------------
function data=fillmatrix_spatial(data,cszn)

[ir,ic]=find(isnan(data)==1);
[irnomissing,icnomissing]=find(isnan(data)==0);%real data
idxmatrixtmp=[];idxmatrixtmp(:,1)=irnomissing(:);idxmatrixtmp(:,2)=icnomissing(:);
for i=1:length(ir)
    id=[ir(i),ic(i)];
    [D,ID]=pdist2(idxmatrixtmp,id,'euclidean','Smallest',1); %D-distance, I-index
    if ~isempty(ID) 
    for j=1:numel(ID)
        r=idxmatrixtmp(ID(j),1);c=idxmatrixtmp(ID(j),2);
        tmpdata=data(r,c);tmpcszn=cszn(r,c); %just one data
    end
    data(ir(i),ic(i))=tmpdata*cszn(ir(i),ic(i))/tmpcszn;
    end
end
end
